### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by dsplice** [fox-it/dissect.target#106]
With a new installation of dissect, the target-* commands throw an error.  It was tried under Ubuntu on WSL2, and on the SIFT workstation.  Same error given to both.

```
dsplice@DESKTOP-KGOQAT4:/mnt/c/Windows/system32$ target-query
Traceback (most recent call last):
  File "/home/dsplice/.local/bin/target-query", line 5, in <module>
    from dissect.target.tools.query import main
  File "/home/dsplice/.local/lib/python3.8/site-packages/dissect/target/__init__.py", line 1, in <module>
    from dissect.target.target import Target
  File "/home/dsplice/.local/lib/python3.8/site-packages/dissect/target/target.py", line 10, in <module>
    from dissect.target import filesystem, loader, plugin, volume
  File "/home/dsplice/.local/lib/python3.8/site-packages/dissect/target/filesystem.py", line 17, in <module>
    from dissect.target.helpers import fsutil, hashutil
  File "/home/dsplice/.local/lib/python3.8/site-packages/dissect/target/helpers/hashutil.py", line 7, in <module>
    from dissect.target.plugins.filesystem.resolver import ResolverPlugin
  File "/home/dsplice/.local/lib/python3.8/site-packages/dissect/target/plugins/filesystem/resolver.py", line 4, in <module>
    from dissect.target.plugin import Plugin, internal
  File "/home/dsplice/.local/lib/python3.8/site-packages/dissect/target/plugin.py", line 35, in <module>
    PluginDescriptor = dict[str, Any]
TypeError: 'type' object is not subscriptable
```

**Comment by Schamper** [comment]
Hi @dsplice, this is an error typically seen when running an older Python version that doesn't yet fully support the type hints used. From your error message it shows you're running Python 3.8. Can you try installing a newer Python version (3.9 recommended) and try again?

**Comment by dsplice** [comment]
I will give it a shot.  Might not be till evening here though.  Makes sense now that I hear it.

**Comment by dsplice** [comment]
Yup, that was the issue.  I thought I had upgraded, however the systems had not updated the links from 3.8 to 3.9.  Please close this issue.
