### ISSUE TITLE
XFS filesystem exception

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.target#284]
When copying files using `target-fs` or listing file system entries using `target-query -f walkfs` on a XFS filesystem, it could occur that a file is not found for some reason. This leads to a the error `FileNotFoundError` after which the commands exit while the file system contains other entries that are not parsed.

Could this be fixed by continuing with reading the filesystem if a file is not found or an other error is raised?

I cannot share the target but I can verify if a fix works for the disk images.

```bash
target-fs <TARGET> cp / --output dir
Traceback (most recent call last):
  File "/usr/lib/pypy/bin/target-fs", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/tools/fs.py", line 124, in main
    args.handler(target, path, args)
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/tools/fs.py", line 46, in cp
    for extract_path in path.rglob("*"):
  File "/usr/lib/pypy/lib/pypy3.9/pathlib.py", line 1190, in rglob
    for p in selector.select_from(self):
  File "/usr/lib/pypy/lib/pypy3.9/pathlib.py", line 611, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/usr/lib/pypy/lib/pypy3.9/pathlib.py", line 558, in _select_from
    with scandir(parent_path) as scandir_it:
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/helpers/fsutil.py", line 467, in scandir
    return _DissectScandirIterator(path.get().scandir())
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/helpers/fsutil.py", line 673, in get
    self._entry = self._fs.get(str(self))
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/filesystem.py", line 1202, in get
    raise FileNotFoundError(full_path)
dissect.target.exceptions.FileNotFoundError: <FILE>


target-query -f walkfs -t <TARGET>
Traceback (most recent call last):
  File "/usr/lib/pypy/bin/target-query", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/tools/query.py", line 292, in main
    raise e
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/tools/query.py", line 277, in main
    for record_entries in entry:
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/plugins/filesystem/walkfs.py", line 34, in walkfs
    for _, record in self.walkfs_ext():
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/plugins/filesystem/walkfs.py", line 40, in walkfs_ext
    for entry in fs.path(root).rglob(pattern):
  File "/usr/lib/pypy/lib/pypy3.9/pathlib.py", line 1190, in rglob
    for p in selector.select_from(self):
  File "/usr/lib/pypy/lib/pypy3.9/pathlib.py", line 611, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/usr/lib/pypy/lib/pypy3.9/pathlib.py", line 558, in _select_from
    with scandir(parent_path) as scandir_it:
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/helpers/fsutil.py", line 467, in scandir
    return _DissectScandirIterator(path.get().scandir())
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/helpers/fsutil.py", line 673, in get
    self._entry = self._fs.get(str(self))
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/filesystems/xfs.py", line 33, in get
    return XfsFilesystemEntry(self, path, self._get_node(path))
  File "/usr/lib/pypy/lib/pypy3.9/site-packages/dissect/target/filesystems/xfs.py", line 39, in _get_node
    raise FileNotFoundError(path)
dissect.target.exceptions.FileNotFoundError: <FILE>
```

**Comment by Schamper** [comment]
Those could/should indeed be made more robust, though the error in itself is also interesting. Are you able to share more details about the file itself? E.g. is it a symlink (and is it a symlink to another filesystem), does the path to it contain symlinks, is it some other special file (socket/device), etc?

**Comment by Zawadidone** [comment]
I will re-open the issue if it occurs with a different disk image.
