### ISSUE TITLE
Windows Registry error: retrieving the root registry key

### ISSUE THREAD

**Issue by Zawadidone** [fox-it/dissect.target#350]
The Windows Registry can be queried using `target-reg` version `3.11.dev34` using the [acquire container](https://files.dissect.tools/images/MSEDGEWIN10_20220708124036.tar)

```bash
target-reg acquire-MSEDGEWIN10.tar -k HKLM
<Target acquire-MSEDGEWIN10.tar>
+ 'HKEY_LOCAL_MACHINE' (None)
  + 'SAM' (2019-03-19 20:55:22.772104+00:00)
  + 'SECURITY' (2019-03-19 13:22:37.837378+00:00)
  + 'SOFTWARE' (2019-03-19 13:24:50.430725+00:00)
  + 'SYSTEM' (2019-03-19 13:22:34.649723+00:00)
```

But when using the `regf` plugins with `target-query` the functions show errors because the registry plugin triggers certain exceptions, which I have enabled ([traceback.print_exc()](https://github.com/fox-it/dissect.target/blob/main/dissect/target/plugins/os/windows/regf/regf.py#L33-L37)).

```bash
Traceback (most recent call last):
  File "dissect.target/dissect/target/plugins/os/windows/regf/regf.py", line 37, in check_compatible
    self.target.registry.root()
  File "dissect.target/dissect/target/plugins/os/windows/registry.py", line 203, in root
    return self.key()
  File "dissect.target/dissect/target/plugins/os/windows/registry.py", line 213, in key
    key = key.strip("\\")
AttributeError: 'NoneType' object has no attribute 'strip'
2023-08-07T18:00:46.525078Z [error    ] <Target acquire-MSEDGEWIN10.tar>: Unsupported plugin for `PluginFunction(name='os.windows.regf.regf.regf', output_type='record', class_object=<class 'dissect.target.plugins.os.windows.regf.regf.RegfPlugin'>, method_name='regf', plugin_desc={'class': 'RegfPlugin', 'module': 'os.windows.regf.regf', 'functions': ['is_compatible', 'regf'], 'exports': ['regf'], 'namespace': None, 'fullname': 'dissect.target.plugins.os.windows.regf.regf.RegfPlugin'})`: Registry plugin not loaded [dissect.target.target]
```

This bug does not occur when using version `3.10` of Dissect Target.

**Comment by Schamper** [comment]
I also noticed this recently (the bug, not specifically with the `regf` plugin. The linked PR should fix this.

**Comment by Zawadidone** [comment]
Can this fix be part of a new patch version`3.11.1`?

**Comment by Zawadidone** [comment]
Nevermind I will use the pre-release when the PR is merged.

**Comment by Zawadidone** [comment]
Okay thank you for that.
