### ISSUE TITLE
target-query --hash function broken

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#413]
The `--hash` function of `target-query` seems to be broken.

Example stacktrace (this also occurs with `walkfs` and `mft` plugins, both on Windows and GNU/Linux):

```
$ target-query -f lnk /tmp/windows10.vmdk --limit 1 --hash

Traceback (most recent call last):
  File "/tmp/dissect/.venv/bin/target-query", line 8, in <module>
    sys.exit(main())
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/tools/utils.py", line 250, in wrapper
    return func(*args, **kwargs)
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/tools/query.py", line 338, in main
    raise e
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/tools/query.py", line 325, in main
    rs.write(hashutil.hash_uri_records(target, record_entries))
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/helpers/hashutil.py", line 70, in hash_uri_records
    uri_record = hash_uri(target, getattr(record, name))
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/helpers/hashutil.py", line 95, in hash_uri
    path = target.resolve(path)
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/plugins/filesystem/resolver.py", line 38, in resolve
    return self.resolve_windows(path, user_sid=user)
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/plugins/filesystem/resolver.py", line 44, in resolve_windows
    path = fsutil.normalize(path, alt_separator=self.target.fs.alt_separator)
  File "/tmp/dissect/.venv/lib/python3.10/site-packages/dissect/target/helpers/fsutil.py", line 46, in normalize
    return re_normalize_sbs_path.sub("/", path)
TypeError: expected string or bytes-like object
```

It seems that the `re_normalize_sbs_path.sub("/", path)` call expects `path` to be a string, while in reality it is a `flow.record.fieldtypes.windows_path` instance. Casting `path` to a string seems to fix the issue.

```python
def normalize(path: str, alt_separator: str = "") -> str:
    if alt_separator == "\\":
        return re_normalize_sbs_path.sub("/", str(path))
    else:
        return re_normalize_path.sub("/", str(path))
```

This was tested using `flow.record==3.12` and `flow.record==3.13.dev2`.

**Comment by pyrco** [comment]
Hi @JSCU-CNI , that's a nasty bug, thanks for reporting it. It turns out this function was completely broken with our move from uri field types to path field types in certain records. I made a fix for it in #432 which should be included in the next release.
