### ISSUE TITLE
QCow2 not detected when not with .qcow2 extension

### ISSUE THREAD

**Issue by Kafow** [fox-it/dissect.target#61]
Hey,
I have been trying to play a bit with target-shell, and noticed a weird behavior.
Whenever i was trying to load a QCow2 without extension, it would fall back to RawContainer, For example:
```bash
└─$ ~/.local/bin/target-shell CentOS-7-x86_64-GenericCloud
2022-10-12T19:42:55.315767Z [warning  ] <Target CentOS-7-x86_64-GenericCloud>: Can't identify volume system, adding as raw volume instead: <RawContainer size=858783744 vs=None> [dissect.target.target] 
Traceback (most recent call last):
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/volume.py", line 270, in open
    return disk.DissectVolumeSystem(fh)
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/helpers/lazy.py", line 52, in __call__
    return self._realattr(*args, **kwargs)
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/volumes/disk.py", line 11, in __init__
    self._disk = disk.Disk(fh)
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/volume/disk/disk.py", line 25, in __init__
    raise DiskError("Unable to detect a valid partition scheme:\n- {}".format("\n- ".join(errors)))
dissect.volume.exceptions.DiskError: Unable to detect a valid partition scheme:
- Invalid MBR boot signature. Expected 0xaa55, got 0x0.
- Invalid MBR boot signature. Expected 0xaa55, got 0x0.
- Invalid APM signature, expected 'PM', got b'QF'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/target.py", line 673, in apply
    disk.vs = volume.open(disk)
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/volume.py", line 272, in open
    raise VolumeSystemError(f"Failed to load volume system for {fh}", cause=e)
dissect.target.exceptions.VolumeSystemError: Failed to load volume system for <RawContainer size=858783744 vs=None>
2022-10-12T19:42:55.340251Z [warning  ] Failed to import <lazyattr dissect.target.volumes.bde.BitlockerVolumeSystem loaded=False> [dissect.target.volume] 
2022-10-12T19:42:55.413489Z [warning  ] <Target CentOS-7-x86_64-GenericCloud>: Can't identify filesystem: <Volume name=None size=858783744 fs=None> [dissect.target.target] 
Traceback (most recent call last):
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/target.py", line 690, in open
    vol.fs = filesystem.open(vol)
  File "/home/ofek/.pyenv/versions/3.9.6/lib/python3.9/site-packages/dissect/target/filesystem.py", line 1369, in open
    raise FilesystemError(f"Failed to open filesystem for {fh}")
dissect.target.exceptions.FilesystemError: Failed to open filesystem for <Volume name=None size=858783744 fs=None>
2022-10-12T19:42:55.856016Z [warning  ] <Target CentOS-7-x86_64-GenericCloud>: Failed to find OS plugin, falling back to default [dissect.target.target] 
```
However, when i tried to load *the same QCow2* now with extension, it would work flawlessly:
```bash
└─$ ~/.local/bin/target-shell CentOS-7-x86_64-GenericCloud.qcow2                                                                                          1 ⨯
2022-10-12T19:43:54.778022Z [warning  ] Failed to import <lazyattr dissect.target.volumes.bde.BitlockerVolumeSystem loaded=False> [dissect.target.volume] 
2022-10-12T19:43:55.375109Z [error    ] <Target CentOS-7-x86_64-GenericCloud.qcow2>: Failed to register network manager interfaces as active. [dissect.target.target] 
```
I tried to debug the source code, and found the problem resides in this piece of code:
`dissect.target.container.detect`
```python
    @classmethod
    def detect(cls, item: Union[list, BinaryIO, Path]) -> bool:
        """Detect if this ``Container`` can handle this file format.

        Args:
            item: The object we want to see if it can be handled by this ``Container``.

        Returns:
            ``True`` if this ``Container`` can be used, ``False`` otherwise.
        """
        i = item[0] if isinstance(item, list) else item
        if hasattr(i, "read"):
            return cls.detect_fh(i, item)
        else:
            return cls.detect_path(i, item)
```
In order for the container to be recognized using file header, you need it to be a BinaryIO stream, which is not being provided here:
`dissect.target.target._load`
```python
    @classmethod
    def _load(cls, path: Union[str, Path], ldr: loader.Loader) -> Target:
        """Internal function that attemps to load a path using a given loader.

        Args:
            path: The path to the target.
            ldr: The loader to use for loading this target.

        Raises:
            TargetError: If it failed to load a target.

        Returns:
            A ``Target`` object with disks, volumes and/or filesystems mapped by the ``ldr`` from the given ``path``.
        """
        target = cls(path) ### The problematic line

        try:
            ldr.map(target)  ### Calls to Container.open which calls to Container.detect
            target._loader = ldr
            target.apply()
            return target
        except Exception as e:
            raise TargetError(f"Failed to load target: {path}", cause=e)

```
I would suggest to add a BinaryIO option in `dissect.target.target._load` for Container.detect to succeed.
Let me know what you think!

Best regards,
Ofek

**Comment by Schamper** [comment]
Nice find! We've always relied on file extensions so never encountered it, but we can certainly change the detection logic for containers to also attempt to detect based on file magic. I'll write up a fix and create a PR soon.
